# Generated by Django 5.2 on 2025-04-28 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_remove_categorie_producats_categorie_producats'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producat',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='producat',
            name='image',
        ),
        migrations.AddField(
            model_name='producat',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='categorie.categorie'),
        ),
        migrations.AddField(
            model_name='producat',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='producat_images', to='product.producatimage'),
        ),
    ]
