# Generated by Django 5.2 on 2025-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_producat_categories_remove_producat_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producat',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producat',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
