# Generated by Django 5.2 on 2025-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='producats',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.product'),
        ),
    ]
