import { ThemeProvider } from "@/context/ThemeProvider";
import Sprinner from "@/utils/Sprinner";
import type { Metadata } from "next";
import "./globals.css";
import LoadingContextProvider from "@/context/LoadingContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LoadingContextProvider>
        <ThemeProvider>
          {children}
          <Sprinner />
        </ThemeProvider>
        </LoadingContextProvider>
      </body>
    </html>
  );
}
