# Generated by Django 5.2 on 2025-04-29 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checkout', '0002_remove_checkout_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_over_courier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hand_over_courier_tracking', models.CharField(blank=True, max_length=255, null=True)),
                ('hand_over_courier_date', models.DateTimeField(blank=True, null=True)),
                ('hand_over_courier_status', models.CharField(choices=[('pending', 'Pending'), ('transit', 'transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('checkout_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='checkout.checkout')),
            ],
        ),
    ]
