# Generated by Django 5.2 on 2025-05-08 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='is_international',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='per_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipping',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('g', 'Grams'), ('lb', 'Pounds'), ('oz', 'Ounces')], default='kg', max_length=10),
        ),
    ]
