# Generated by Django 5.2 on 2025-04-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='producats',
        ),
        migrations.AddField(
            model_name='categorie',
            name='producats',
            field=models.ManyToManyField(blank=True, related_name='producats', to='product.producat'),
        ),
    ]
