# Generated by Django 5.2 on 2025-04-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('modaretor', 'Modaretor'), ('seller', 'Seller'), ('user', 'User')], default='user', max_length=50),
        ),
    ]
