# Generated by Django 5.2 on 2025-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='nid_back',
            field=models.ImageField(blank=True, null=True, upload_to='nid/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nid_font',
            field=models.ImageField(blank=True, null=True, upload_to='nid/'),
        ),
    ]
