# Generated by Django 5.2 on 2025-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkout_date', models.DateTimeField(auto_now_add=True)),
                ('shipping_city', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_state', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_country', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
